### ISSUE TITLE
how to enable the intel igpu?

### ISSUE THREAD

**Issue by maverickchangithub** [norton287/Gigabyte-Z370-HD3P#2]
Would you please tell me more specific how to enable IGPU?

> To upgrade to macOS 10.4.4 with IGPU running in headless with a discrete GPU as your main driver, you need to delete the device entry in your config.plist and remove the Platform ID. Also, you want to check Inject Intel as well.

I am not quite understand this line.
I have the same board , it has only 1 HDMI port , 1 dvi port and a useless vga port .
Which port should i use?
I am using i5-8400 cpu and tried inject intel , it does not work.
Is it required a AMD dedicated card installed as a partner? 

Many thanks!

**Comment by norton287** [comment]
That is if you still wanted to run the iGPU in headless mode with 10.14, you had to remove the device properties from the config.plist and just leave the check on Inject Intel.  

 

If you want to run your iGPU as you main video without an external drive like an AMD or other brands then you need to look and read these because you will have to setup the device properties of the internal Intel iGPU:

 

Hackintool builds the patches to patch config.plist for the card:  https://www.insanelymac.com/forum/topic/335018-hackintool-v3xx/

You will need to read this on Intel FrameBuffer Patching with Whatevergreen:  https://www.insanelymac.com/forum/topic/334899-intel-framebuffer-patching-using-whatevergreen/

 

Both link to several other websites to review, but if you follow them precisely, you should have your Intel iGPU running.

 

I got bored reading and just set up the intel card as a headless configuration and bought a Saphire Pulse RX580 since it is natively supported.  I recently disable my Intel iGPU since Whatever green handles the hardware acceleration issue with running without an Intel iGPU.

 

John

 

BTW my board only has one HDMI port so you could have a different revision than me.

**Comment by maverickchangithub** [comment]
thank you , now i understand it .

btw ,  i tried using igpu as main display , no luck at all. hdmi will cause purple screen and cannot be fixed . this motherboard is not a good choice , other board with at least one DP port will save lot of trouble.

**Comment by norton287** [comment]
Absolutely!
________________________________
